<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.13">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Anissa Chan">
<meta name="dcterms.date" content="2026-04-23">

<title>A/B Testing a Call to Action – quarto_website</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ac077c1e730dfeb5e42400639d17284e.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-39fc3590519fe04b9be5cf16d3cc69a0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">quarto_website</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html"> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#the-ab-test-as-a-statistical-problem" id="toc-the-ab-test-as-a-statistical-problem" class="nav-link" data-scroll-target="#the-ab-test-as-a-statistical-problem"><span class="header-section-number">2</span> The A/B Test as a Statistical Problem</a></li>
  <li><a href="#simulating-data" id="toc-simulating-data" class="nav-link" data-scroll-target="#simulating-data"><span class="header-section-number">3</span> Simulating Data</a></li>
  <li><a href="#the-law-of-large-numbers" id="toc-the-law-of-large-numbers" class="nav-link" data-scroll-target="#the-law-of-large-numbers"><span class="header-section-number">4</span> The Law of Large Numbers</a></li>
  <li><a href="#bootstrap-standard-errors" id="toc-bootstrap-standard-errors" class="nav-link" data-scroll-target="#bootstrap-standard-errors"><span class="header-section-number">5</span> Bootstrap Standard Errors</a></li>
  <li><a href="#the-central-limit-theorem" id="toc-the-central-limit-theorem" class="nav-link" data-scroll-target="#the-central-limit-theorem"><span class="header-section-number">6</span> The Central Limit Theorem</a></li>
  <li><a href="#hypothesis-testing" id="toc-hypothesis-testing" class="nav-link" data-scroll-target="#hypothesis-testing"><span class="header-section-number">7</span> Hypothesis Testing</a></li>
  <li><a href="#the-ab-test-as-a-regression" id="toc-the-ab-test-as-a-regression" class="nav-link" data-scroll-target="#the-ab-test-as-a-regression"><span class="header-section-number">8</span> The A/B Test as a Regression</a></li>
  <li><a href="#the-problem-with-peeking" id="toc-the-problem-with-peeking" class="nav-link" data-scroll-target="#the-problem-with-peeking"><span class="header-section-number">9</span> The Problem with Peeking</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">10</span> Conclusion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">A/B Testing a Call to Action</h1>
<p class="subtitle lead">Simulating Key Ideas from Classical Frequentist Statistics</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Anissa Chan </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 23, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">1</span> Introduction</h2>
<p>On my website homepage, I ask visitors to sign up for a newsletter. That little prompt might look like a minor design choice, but in practice the wording of a call to action (CTA) can change how many people convert. In this post I compare two versions of the same prompt:</p>
<ul>
<li><strong>CTA A:</strong> “Sign up for our newsletter here!”</li>
<li><strong>CTA B:</strong> “Stay up to date by signing up!”</li>
</ul>
<p>The business question is simple: which CTA generates more sign-ups? The right way to answer it is not to rely on instinct, but to run an <strong>A/B test</strong>. In an A/B test, incoming visitors are randomly assigned to see one version or the other. Because the assignment is random, any difference in conversion rates can be attributed to the CTA itself rather than to who happened to visit the site.</p>
<p>What makes this a useful example is that it also illustrates the core ideas of classical frequentist statistics. We will simulate a clean A/B test, estimate the treatment effect, study how that estimator behaves as the sample grows, quantify uncertainty with the bootstrap, connect the result to the Central Limit Theorem, and finish with hypothesis testing and the dangers of peeking at results too early.</p>
</section>
<section id="the-ab-test-as-a-statistical-problem" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="the-ab-test-as-a-statistical-problem"><span class="header-section-number">2</span> The A/B Test as a Statistical Problem</h2>
<p>For each visitor, the outcome is binary: either they sign up for the newsletter or they do not. That means each observation can be modeled as a draw from a <strong>Bernoulli</strong> distribution with parameter <span class="math inline">\(\pi\)</span>, the probability of signing up.</p>
<p>Because the CTA may affect behavior, we allow that probability to differ by group. If a visitor sees CTA A, their outcome is a Bernoulli random variable with parameter <span class="math inline">\(\pi_A\)</span>. If they see CTA B, their outcome is a Bernoulli random variable with parameter <span class="math inline">\(\pi_B\)</span>.</p>
<p>The quantity we care about is the difference in sign-up rates,</p>
<p><span class="math display">\[
\theta = \pi_A - \pi_B.
\]</span></p>
<p>A positive value of <span class="math inline">\(\theta\)</span> means CTA A performs better; a negative value means CTA B performs better. Our estimator is the difference in sample means,</p>
<p><span class="math display">\[
\hat\theta = \bar X_A - \bar X_B.
\]</span></p>
<p>Because each observation is either 0 or 1, the sample mean is just the sample proportion of sign-ups. So in this setting <span class="math inline">\(\bar X_A = \hat\pi_A\)</span> and <span class="math inline">\(\bar X_B = \hat\pi_B\)</span>. The estimator <span class="math inline">\(\hat\theta\)</span> is therefore the observed lift in conversion rate between the two CTAs.</p>
</section>
<section id="simulating-data" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="simulating-data"><span class="header-section-number">3</span> Simulating Data</h2>
<p>In a real experiment we would not know the true values of <span class="math inline">\(\pi_A\)</span> and <span class="math inline">\(\pi_B\)</span>. That is exactly why we would run the test in the first place. For this post, though, simulation is useful because it lets us choose the truth ourselves and then check whether our statistical tools recover it.</p>
<p>I set <span class="math inline">\(\pi_A = 0.22\)</span> and <span class="math inline">\(\pi_B = 0.18\)</span>, so the true treatment effect is</p>
<p><span class="math display">\[
\theta = 0.22 - 0.18 = 0.04.
\]</span></p>
<p>That means CTA A is truly better by 4 percentage points. I then simulate 1,000 visitors in each group.</p>
<div id="cell-simulate-data" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>summary_df <span class="op">=</span> pd.DataFrame({</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Group"</span>:                    [<span class="st">"CTA A"</span>, <span class="st">"CTA B"</span>],</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"True signup probability"</span>:  [pi_A, pi_B],</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Sample size"</span>:              [<span class="bu">len</span>(cta_a), <span class="bu">len</span>(cta_b)],</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Observed signup rate"</span>:     [pi_hat_A, pi_hat_B],</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>summary_df.style.hide(axis<span class="op">=</span><span class="st">"index"</span>).<span class="bu">format</span>({</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"True signup probability"</span>: <span class="st">"</span><span class="sc">{:.1%}</span><span class="st">"</span>,</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Observed signup rate"</span>:    <span class="st">"</span><span class="sc">{:.1%}</span><span class="st">"</span>,</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Sample size"</span>:             <span class="st">"</span><span class="sc">{:.0f}</span><span class="st">"</span>,</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>})</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div id="simulate-data" class="cell-output cell-output-display" data-execution_count="2">
<style type="text/css">
</style>

<table id="T_b7cc6" class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th id="T_b7cc6_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">Group</th>
<th id="T_b7cc6_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">True signup probability</th>
<th id="T_b7cc6_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">Sample size</th>
<th id="T_b7cc6_level0_col3" class="col_heading level0 col3" data-quarto-table-cell-role="th">Observed signup rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td id="T_b7cc6_row0_col0" class="data row0 col0">CTA A</td>
<td id="T_b7cc6_row0_col1" class="data row0 col1">22.0%</td>
<td id="T_b7cc6_row0_col2" class="data row0 col2">1000</td>
<td id="T_b7cc6_row0_col3" class="data row0 col3">22.6%</td>
</tr>
<tr class="even">
<td id="T_b7cc6_row1_col0" class="data row1 col0">CTA B</td>
<td id="T_b7cc6_row1_col1" class="data row1 col1">18.0%</td>
<td id="T_b7cc6_row1_col2" class="data row1 col2">1000</td>
<td id="T_b7cc6_row1_col3" class="data row1 col3">17.9%</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="e299846c" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display cell-output-markdown">
<p>In this simulated experiment, CTA A converted <strong>22.6%</strong> of visitors and CTA B converted <strong>17.9%</strong>. The estimated lift was <strong>4.7%</strong>, which is close to the true effect of <strong>4.0%</strong> but not identical to it—exactly what we should expect from random sampling.</p>
</div>
</div>
</section>
<section id="the-law-of-large-numbers" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="the-law-of-large-numbers"><span class="header-section-number">4</span> The Law of Large Numbers</h2>
<p>The <strong>Law of Large Numbers (LLN)</strong> says that as the sample size grows, the sample mean converges to the population mean. In the A/B testing setting, that means the cumulative conversion rate within each group should settle down near its true probability, and the difference between those cumulative rates should settle down near the true treatment effect.</p>
<p>To show that, I track the running conversion rate for CTA A and CTA B separately. After the first <span class="math inline">\(k\)</span> visitors in each group, the running treatment effect is just the difference between the two cumulative sample conversion rates,</p>
<p><span class="math display">\[
\hat\theta_k = \left(\frac{1}{k}\sum_{i=1}^k X_{Ai}\right) - \left(\frac{1}{k}\sum_{i=1}^k X_{Bi}\right).
\]</span></p>
<div id="lln-code" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>running_pi_A <span class="op">=</span> np.cumsum(cta_a) <span class="op">/</span> np.arange(<span class="dv">1</span>, n <span class="op">+</span> <span class="dv">1</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>running_pi_B <span class="op">=</span> np.cumsum(cta_b) <span class="op">/</span> np.arange(<span class="dv">1</span>, n <span class="op">+</span> <span class="dv">1</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>running_theta <span class="op">=</span> running_pi_A <span class="op">-</span> running_pi_B</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="cell-lln-plot" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/lln-plot-output-1.png" id="lln-plot" width="754" height="465" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>At the beginning of the experiment, the running rates move around a lot because a few extra sign-ups can change the estimate substantially. As more visitors arrive, both group averages settle down: CTA A stabilizes near 0.22, CTA B stabilizes near 0.18, and their difference settles near the true lift of 0.04. That is exactly the LLN in action.</p>
<p>This is the first major promise of frequentist inference: repeated sampling gives us a principled way to think about how close our estimators should be to the truth.</p>
</section>
<section id="bootstrap-standard-errors" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="bootstrap-standard-errors"><span class="header-section-number">5</span> Bootstrap Standard Errors</h2>
<p>Once we have a point estimate, the next question is precision. A lift estimate of 4 or 5 percentage points is much more convincing when it comes with a small standard error than a large one. This is where the <strong>bootstrap</strong> becomes useful.</p>
<p>The bootstrap is a resampling method. Instead of deriving the variability of <span class="math inline">\(\hat\theta\)</span> from theory alone, we repeatedly resample from the observed data—with replacement—recompute the estimator on each bootstrap sample, and use the spread of those resampled estimates as an approximation of the standard error.</p>
<div id="bootstrap-code" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>rng_boot   <span class="op">=</span> np.random.default_rng(<span class="dv">496</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>B          <span class="op">=</span> <span class="dv">1000</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>boot_theta <span class="op">=</span> np.empty(B)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> b <span class="kw">in</span> <span class="bu">range</span>(B):</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    a_star       <span class="op">=</span> rng_boot.choice(cta_a, size<span class="op">=</span>n, replace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    b_star       <span class="op">=</span> rng_boot.choice(cta_b, size<span class="op">=</span>n, replace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    boot_theta[b] <span class="op">=</span> a_star.mean() <span class="op">-</span> b_star.mean()</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>boot_se     <span class="op">=</span> boot_theta.std(ddof<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>analytic_se <span class="op">=</span> np.sqrt(</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>    pi_hat_A <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> pi_hat_A) <span class="op">/</span> n <span class="op">+</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>    pi_hat_B <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> pi_hat_B) <span class="op">/</span> n</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>ci_low  <span class="op">=</span> theta_hat <span class="op">-</span> <span class="fl">1.96</span> <span class="op">*</span> boot_se</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>ci_high <span class="op">=</span> theta_hat <span class="op">+</span> <span class="fl">1.96</span> <span class="op">*</span> boot_se</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The plot below shows the distribution of those 1,000 bootstrapped estimates. A good bootstrap distribution should be approximately bell-shaped and centered on the observed estimate.</p>
<div id="cell-bootstrap-plot" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/bootstrap-plot-output-1.png" id="bootstrap-plot" width="754" height="464" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="cell-bootstrap-results" class="cell" data-execution_count="8">
<div id="bootstrap-results" class="cell-output cell-output-display" data-execution_count="8">
<style type="text/css">
</style>

<table id="T_7db93" class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th id="T_7db93_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">Quantity</th>
<th id="T_7db93_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td id="T_7db93_row0_col0" class="data row0 col0">Observed lift ($\hat{\theta}$)</td>
<td id="T_7db93_row0_col1" class="data row0 col1">0.0470</td>
</tr>
<tr class="even">
<td id="T_7db93_row1_col0" class="data row1 col0">Bootstrap standard error</td>
<td id="T_7db93_row1_col1" class="data row1 col1">0.0179</td>
</tr>
<tr class="odd">
<td id="T_7db93_row2_col0" class="data row2 col0">Analytical standard error</td>
<td id="T_7db93_row2_col1" class="data row2 col1">0.0179</td>
</tr>
<tr class="even">
<td id="T_7db93_row3_col0" class="data row3 col0">95% CI lower bound</td>
<td id="T_7db93_row3_col1" class="data row3 col1">0.0120</td>
</tr>
<tr class="odd">
<td id="T_7db93_row4_col0" class="data row4 col0">95% CI upper bound</td>
<td id="T_7db93_row4_col1" class="data row4 col1">0.0820</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="1e76385a" class="cell" data-execution_count="9">
<div class="cell-output cell-output-display cell-output-markdown">
<p>The bootstrap standard error is <strong>0.0179</strong>, while the analytical standard error is <strong>0.0179</strong>. They are very close, which is reassuring: the resampling approach and the Bernoulli formula are telling essentially the same story about uncertainty. Using the bootstrap standard error, the 95% confidence interval for the treatment effect is <strong>(0.0120, 0.0820)</strong>. In practical terms, this interval says that the data are consistent with CTA A improving the sign-up rate by somewhere between <strong>1.2%</strong> and <strong>8.2%</strong>.</p>
</div>
</div>
<p>The important interpretation point is that the parameter itself is fixed, not random. The random object is the interval-producing procedure. A 95% confidence interval is a method that would cover the true effect 95% of the time if we repeated the experiment many times under the same conditions.</p>
</section>
<section id="the-central-limit-theorem" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="the-central-limit-theorem"><span class="header-section-number">6</span> The Central Limit Theorem</h2>
<p>The <strong>Central Limit Theorem (CLT)</strong> says that the sampling distribution of a sample mean becomes approximately Normal as the sample size gets large, regardless of the shape of the underlying population distribution. Since our estimator is the difference between two sample means, the same logic applies here.</p>
<p>That result is especially useful because the raw data in this problem are not Normal at all—they are Bernoulli variables that take only the values 0 and 1. Even so, the average of many such observations behaves more and more like a bell-shaped random variable.</p>
<p>To illustrate that, I repeated the A/B experiment 1,000 times for each of four sample sizes: <span class="math inline">\(n \in \{25, 50, 100, 500\}\)</span>. Each time I computed <span class="math inline">\(\hat\theta = \bar X_A - \bar X_B\)</span>, then plotted the distribution of those 1,000 estimates together with the Normal curve predicted by theory.</p>
<div id="cell-clt-plot" class="cell" data-execution_count="10">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/clt-plot-output-1.png" id="clt-plot" width="1043" height="754" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>At <span class="math inline">\(n = 25\)</span>, the histogram is rough and the Normal overlay is a poor fit. By <span class="math inline">\(n = 100\)</span>, the shape is already smooth and symmetric, and by <span class="math inline">\(n = 500\)</span> the empirical distribution and the theoretical Normal are nearly indistinguishable. That is the CLT in action.</p>
<p>The practical payoff is enormous: once the sampling distribution is approximately Normal, we can use familiar z-statistics, p-values, and confidence intervals to summarize the evidence in our experiment.</p>
</section>
<section id="hypothesis-testing" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="hypothesis-testing"><span class="header-section-number">7</span> Hypothesis Testing</h2>
<p>A <strong>hypothesis test</strong> formalizes the question of whether the observed difference between CTA A and CTA B is large enough to count as evidence against “no effect.” Here the null and alternative are</p>
<p><span class="math display">\[
H_0: \theta = 0
\qquad \text{versus} \qquad
H_1: \theta \neq 0.
\]</span></p>
<p>Under the null, the two CTAs have the same true sign-up rate. To evaluate that claim, I use a large-sample Wald-style z-test, which standardizes the estimated lift by its estimated standard error:</p>
<p><span class="math display">\[
z = \frac{\hat\theta - 0}{SE(\hat\theta)}.
\]</span></p>
<p>This standardization matters for three reasons.</p>
<ol type="1">
<li>By the CLT, <span class="math inline">\(\hat\theta\)</span> is approximately Normal in large samples.</li>
<li>Under <span class="math inline">\(H_0\)</span>, that approximate Normal distribution is centered at 0.</li>
<li>Dividing by the standard error converts the estimate into a unit-free quantity that is approximately standard Normal under the null, which lets us compute a p-value.</li>
</ol>
<p>In this post I estimate that standard error directly from the two observed Bernoulli samples. That is slightly different from the pooled standard error sometimes used in an introductory two-proportion z-test, but the logic is the same: in a large sample, both approaches lead to essentially the same conclusion here.</p>
<p>This is often casually called a “t-test,” but in this Bernoulli setting the label is slightly misleading. The classical t-statistic has an exact t-distribution when the data are Normally distributed and the variance is estimated. Here the raw data are binary, not Normal, so there is no exact t-distribution result to lean on. What justifies the test is the CLT, which makes the statistic approximately Normal in large samples. In practice, once the sample is large, the difference between a t reference distribution and a standard Normal reference distribution is negligible.</p>
<div id="cell-hypothesis-results" class="cell" data-execution_count="11">
<div id="hypothesis-results" class="cell-output cell-output-display" data-execution_count="11">
<style type="text/css">
</style>

<table id="T_a6446" class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th id="T_a6446_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">Statistic</th>
<th id="T_a6446_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td id="T_a6446_row0_col0" class="data row0 col0">Estimated lift</td>
<td id="T_a6446_row0_col1" class="data row0 col1">0.0470</td>
</tr>
<tr class="even">
<td id="T_a6446_row1_col0" class="data row1 col0">Standard error</td>
<td id="T_a6446_row1_col1" class="data row1 col1">0.0179</td>
</tr>
<tr class="odd">
<td id="T_a6446_row2_col0" class="data row2 col0">z-statistic</td>
<td id="T_a6446_row2_col1" class="data row2 col1">2.6197</td>
</tr>
<tr class="even">
<td id="T_a6446_row3_col0" class="data row3 col0">p-value</td>
<td id="T_a6446_row3_col1" class="data row3 col1">0.0088</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="ee3edcfa" class="cell" data-execution_count="12">
<div class="cell-output cell-output-display cell-output-markdown">
<p>The test statistic is <strong>2.62</strong>, which corresponds to a two-sided p-value of <strong>0.0088</strong>. At the conventional 5% level, we therefore <strong>reject</strong> the null hypothesis of no effect. In plain English: this simulated dataset provides fairly strong evidence that CTA A outperforms CTA B, and the estimated advantage is about <strong>4.7%</strong>.</p>
</div>
</div>
</section>
<section id="the-ab-test-as-a-regression" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="the-ab-test-as-a-regression"><span class="header-section-number">8</span> The A/B Test as a Regression</h2>
<p>The same comparison can be written as a simple regression. Stack the two groups into one dataset with an outcome variable <span class="math inline">\(Y_i\)</span> that equals 1 if visitor <span class="math inline">\(i\)</span> signs up and 0 otherwise, and a treatment indicator <span class="math inline">\(D_i\)</span> that equals 1 if the visitor saw CTA A and 0 if they saw CTA B. Then estimate</p>
<p><span class="math display">\[
Y_i = \beta_0 + \beta_1 D_i + \varepsilon_i.
\]</span></p>
<p>This specification has a clean interpretation:</p>
<ol type="1">
<li><span class="math inline">\(\beta_0\)</span> is the mean outcome for the control group (CTA B), so it estimates <span class="math inline">\(\pi_B\)</span>.</li>
<li><span class="math inline">\(\beta_0 + \beta_1\)</span> is the mean outcome for the treatment group (CTA A), so it estimates <span class="math inline">\(\pi_A\)</span>.</li>
<li>Therefore <span class="math inline">\(\beta_1 = \pi_A - \pi_B = \theta\)</span>, which means the OLS slope coefficient is exactly the treatment effect we have been estimating all along.</li>
</ol>
<div id="cell-regression-results" class="cell" data-execution_count="13">
<div id="regression-results" class="cell-output cell-output-display" data-execution_count="13">
<style type="text/css">
</style>

<table id="T_35773" class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th id="T_35773_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">Term</th>
<th id="T_35773_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">Estimate</th>
<th id="T_35773_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">Std. Error</th>
<th id="T_35773_level0_col3" class="col_heading level0 col3" data-quarto-table-cell-role="th">t-statistic</th>
<th id="T_35773_level0_col4" class="col_heading level0 col4" data-quarto-table-cell-role="th">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td id="T_35773_row0_col0" class="data row0 col0">Intercept (CTA B mean)</td>
<td id="T_35773_row0_col1" class="data row0 col1">0.1790</td>
<td id="T_35773_row0_col2" class="data row0 col2">0.0127</td>
<td id="T_35773_row0_col3" class="data row0 col3">14.1027</td>
<td id="T_35773_row0_col4" class="data row0 col4">0.0000</td>
</tr>
<tr class="even">
<td id="T_35773_row1_col0" class="data row1 col0">CTA A indicator</td>
<td id="T_35773_row1_col1" class="data row1 col1">0.0470</td>
<td id="T_35773_row1_col2" class="data row1 col2">0.0180</td>
<td id="T_35773_row1_col3" class="data row1 col3">2.6184</td>
<td id="T_35773_row1_col4" class="data row1 col4">0.0089</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="cell-comparison-table" class="cell" data-execution_count="14">
<div id="comparison-table" class="cell-output cell-output-display" data-execution_count="14">
<style type="text/css">
</style>

<table id="T_85747" class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th id="T_85747_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">Approach</th>
<th id="T_85747_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">Estimate</th>
<th id="T_85747_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">SE</th>
<th id="T_85747_level0_col3" class="col_heading level0 col3" data-quarto-table-cell-role="th">Test statistic</th>
<th id="T_85747_level0_col4" class="col_heading level0 col4" data-quarto-table-cell-role="th">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td id="T_85747_row0_col0" class="data row0 col0">Two-sample test</td>
<td id="T_85747_row0_col1" class="data row0 col1">0.0470</td>
<td id="T_85747_row0_col2" class="data row0 col2">0.0179</td>
<td id="T_85747_row0_col3" class="data row0 col3">2.6197</td>
<td id="T_85747_row0_col4" class="data row0 col4">0.0088</td>
</tr>
<tr class="even">
<td id="T_85747_row1_col0" class="data row1 col0">Regression slope</td>
<td id="T_85747_row1_col1" class="data row1 col1">0.0470</td>
<td id="T_85747_row1_col2" class="data row1 col2">0.0180</td>
<td id="T_85747_row1_col3" class="data row1 col3">2.6184</td>
<td id="T_85747_row1_col4" class="data row1 col4">0.0089</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The point estimates are identical, and the test statistics and p-values are essentially the same. Any small difference in the standard errors comes from the exact variance formula being used. In this binary-outcome setting, OLS is acting as a simple linear probability model, so the regression is not adding new information in the two-group case—but it <em>is</em> giving us a more general language.</p>
<p>That matters because real experiments rarely stay this simple. Once you understand the regression framing, it becomes natural to add customer covariates, interactions, multiple treatment arms, or fixed effects while preserving the same basic logic of causal comparison.</p>
</section>
<section id="the-problem-with-peeking" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="the-problem-with-peeking"><span class="header-section-number">9</span> The Problem with Peeking</h2>
<p>Now for the part that gets people in trouble.</p>
<p>Suppose my boss does not want to wait until 1,000 visitors have been assigned to each CTA. Instead, she wants to test after every 100 visitors per group and stop the experiment as soon as any interim result is significant at the 5% level. That sounds efficient, but under classical frequentist statistics it changes the error rate of the procedure.</p>
<p>A single hypothesis test at <span class="math inline">\(\alpha = 0.05\)</span> has a 5% chance of a false positive when the null is true. But if we keep peeking at accumulating data, every interim look is another chance to get lucky noise that crosses the significance threshold. The overall chance of at least one false rejection can become much larger than 5%.</p>
<p>To show that, I simulated 10,000 experiments under a world where the null is true: <span class="math inline">\(\pi_A = \pi_B = 0.20\)</span>. In each experiment, I checked the p-value after 100, 200, 300, …, 1,000 visitors per group. I then recorded whether <strong>any</strong> of those 10 looks produced a significant result.</p>
<div id="cell-peeking-summary-table" class="cell" data-execution_count="15">
<div id="peeking-summary-table" class="cell-output cell-output-display" data-execution_count="15">
<style type="text/css">
</style>

<table id="T_3bc38" class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th id="T_3bc38_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">Procedure</th>
<th id="T_3bc38_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">Empirical false positive rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td id="T_3bc38_row0_col0" class="data row0 col0">Single look at n = 1,000</td>
<td id="T_3bc38_row0_col1" class="data row0 col1">5.5%</td>
</tr>
<tr class="even">
<td id="T_3bc38_row1_col0" class="data row1 col0">Peek every 100 visitors (10 looks)</td>
<td id="T_3bc38_row1_col1" class="data row1 col1">19.1%</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="cell-peeking-plots" class="cell" data-execution_count="16">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/peeking-plots-output-1.png" id="peeking-plots" width="1234" height="465" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="5f3373cc" class="cell" data-execution_count="17">
<div class="cell-output cell-output-display cell-output-markdown">
<p>With one pre-specified look at the end of the experiment, the empirical false positive rate is about <strong>5.5%</strong>—right at the nominal 5%. But with repeated peeking, the false positive rate climbs to about <strong>19.1%</strong>. The left-hand chart makes this even clearer: the contamination does not arrive all at once; it accumulates with every additional look, so stopping early actually makes the problem worse, not better. An apparently harmless habit of checking results early roughly <strong>3×</strong> the chance of declaring a winner when no real difference exists.</p>
</div>
</div>
<p>This is why classical A/B testing requires discipline. Either commit in advance to a fixed sample size and a single final analysis, or use a stopping rule that explicitly adjusts for interim looks (e.g., sequential testing methods such as the sequential probability ratio test or group sequential designs). Without that adjustment, “just checking in” is not harmless—it changes the statistical procedure itself.</p>
</section>
<section id="conclusion" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="conclusion"><span class="header-section-number">10</span> Conclusion</h2>
<p>This simple CTA experiment turns out to be a compact tour of classical frequentist statistics.</p>
<ul>
<li>Modeling each visitor as a Bernoulli draw gave us a clean estimand: the difference in conversion rates.</li>
<li>The Law of Large Numbers showed why the sample difference in means is a sensible estimator.</li>
<li>The bootstrap and the analytical formula both quantified uncertainty through a standard error, and agreed closely with each other.</li>
<li>The Central Limit Theorem justified approximate Normal inference even though the raw data were binary.</li>
<li>Hypothesis testing translated the estimate into a z-statistic and a p-value.</li>
<li>Regression reproduced the same comparison in a framework that scales naturally to richer experimental designs.</li>
<li>And the peeking simulation showed how easy it is to break nominal Type I error guarantees by repeatedly checking for significance.</li>
</ul>
<p>That is the frequentist mindset in one example: probability is about repeated sampling, estimators are random because samples are random, and the reliability of our conclusions depends as much on the procedure we use as on the specific numbers we observe.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>